// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClientDevice
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "connected")]
        public bool Connected;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "last_connected")]
        public SpacetimeDB.Timestamp LastConnected;
        [DataMember(Name = "last_disconnected")]
        public SpacetimeDB.Timestamp LastDisconnected;

        public ClientDevice(
            SpacetimeDB.Identity Identity,
            bool Connected,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp LastConnected,
            SpacetimeDB.Timestamp LastDisconnected
        )
        {
            this.Identity = Identity;
            this.Connected = Connected;
            this.CreatedAt = CreatedAt;
            this.LastConnected = LastConnected;
            this.LastDisconnected = LastDisconnected;
        }

        public ClientDevice()
        {
        }
    }
}
