// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Conversation
    {
        [DataMember(Name = "conversation_id")]
        public ulong ConversationId;
        [DataMember(Name = "last_message_at")]
        public SpacetimeDB.Timestamp LastMessageAt;
        [DataMember(Name = "participants_hash")]
        public string ParticipantsHash;
        [DataMember(Name = "name")]
        public string? Name;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "created_by")]
        public SpacetimeDB.Identity CreatedBy;
        [DataMember(Name = "status")]
        public ConversationStatus Status;

        public Conversation(
            ulong ConversationId,
            SpacetimeDB.Timestamp LastMessageAt,
            string ParticipantsHash,
            string? Name,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Identity CreatedBy,
            ConversationStatus Status
        )
        {
            this.ConversationId = ConversationId;
            this.LastMessageAt = LastMessageAt;
            this.ParticipantsHash = ParticipantsHash;
            this.Name = Name;
            this.CreatedAt = CreatedAt;
            this.CreatedBy = CreatedBy;
            this.Status = Status;
        }

        public Conversation()
        {
            this.ParticipantsHash = "";
        }
    }
}
