// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConversationParticipant
    {
        [DataMember(Name = "participant_id")]
        public ulong ParticipantId;
        [DataMember(Name = "conversation_id")]
        public ulong ConversationId;
        [DataMember(Name = "participant_identity")]
        public SpacetimeDB.Identity ParticipantIdentity;
        [DataMember(Name = "joined_at")]
        public SpacetimeDB.Timestamp JoinedAt;
        [DataMember(Name = "last_viewed_at")]
        public SpacetimeDB.Timestamp LastViewedAt;

        public ConversationParticipant(
            ulong ParticipantId,
            ulong ConversationId,
            SpacetimeDB.Identity ParticipantIdentity,
            SpacetimeDB.Timestamp JoinedAt,
            SpacetimeDB.Timestamp LastViewedAt
        )
        {
            this.ParticipantId = ParticipantId;
            this.ConversationId = ConversationId;
            this.ParticipantIdentity = ParticipantIdentity;
            this.JoinedAt = JoinedAt;
            this.LastViewedAt = LastViewedAt;
        }

        public ConversationParticipant()
        {
        }
    }
}
