// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MediaMetadata
    {
        [DataMember(Name = "media_id")]
        public ulong MediaId;
        [DataMember(Name = "object_key")]
        public string ObjectKey;
        [DataMember(Name = "owner_identity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "original_filename")]
        public string OriginalFilename;
        [DataMember(Name = "content_type")]
        public string ContentType;
        [DataMember(Name = "file_size")]
        public ulong? FileSize;
        [DataMember(Name = "upload_status")]
        public UploadStatus UploadStatus;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "upload_completed_at")]
        public SpacetimeDB.Timestamp? UploadCompletedAt;

        public MediaMetadata(
            ulong MediaId,
            string ObjectKey,
            SpacetimeDB.Identity OwnerIdentity,
            string OriginalFilename,
            string ContentType,
            ulong? FileSize,
            UploadStatus UploadStatus,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? UploadCompletedAt
        )
        {
            this.MediaId = MediaId;
            this.ObjectKey = ObjectKey;
            this.OwnerIdentity = OwnerIdentity;
            this.OriginalFilename = OriginalFilename;
            this.ContentType = ContentType;
            this.FileSize = FileSize;
            this.UploadStatus = UploadStatus;
            this.CreatedAt = CreatedAt;
            this.UploadCompletedAt = UploadCompletedAt;
        }

        public MediaMetadata()
        {
            this.ObjectKey = "";
            this.OriginalFilename = "";
            this.ContentType = "";
        }
    }
}
