// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Message
    {
        [DataMember(Name = "message_id")]
        public ulong MessageId;
        [DataMember(Name = "conversation_id")]
        public ulong ConversationId;
        [DataMember(Name = "sender_identity")]
        public SpacetimeDB.Identity SenderIdentity;
        [DataMember(Name = "content")]
        public string Content;
        [DataMember(Name = "last_edited_at")]
        public SpacetimeDB.Timestamp? LastEditedAt;
        [DataMember(Name = "message_type")]
        public MessageType MessageType;
        [DataMember(Name = "is_deleted")]
        public bool IsDeleted;
        [DataMember(Name = "sent_at")]
        public SpacetimeDB.Timestamp SentAt;

        public Message(
            ulong MessageId,
            ulong ConversationId,
            SpacetimeDB.Identity SenderIdentity,
            string Content,
            SpacetimeDB.Timestamp? LastEditedAt,
            MessageType MessageType,
            bool IsDeleted,
            SpacetimeDB.Timestamp SentAt
        )
        {
            this.MessageId = MessageId;
            this.ConversationId = ConversationId;
            this.SenderIdentity = SenderIdentity;
            this.Content = Content;
            this.LastEditedAt = LastEditedAt;
            this.MessageType = MessageType;
            this.IsDeleted = IsDeleted;
            this.SentAt = SentAt;
        }

        public Message()
        {
            this.Content = "";
        }
    }
}
