// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OrganizationMemberRequest
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "organization_id")]
        public uint OrganizationId;
        [DataMember(Name = "requester_identity")]
        public SpacetimeDB.Identity RequesterIdentity;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public OrganizationMemberRequest(
            ulong Id,
            uint OrganizationId,
            SpacetimeDB.Identity RequesterIdentity,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.OrganizationId = OrganizationId;
            this.RequesterIdentity = RequesterIdentity;
            this.CreatedAt = CreatedAt;
        }

        public OrganizationMemberRequest()
        {
        }
    }
}
