// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OrganizationNotice
    {
        [DataMember(Name = "notice_id")]
        public ulong NoticeId;
        [DataMember(Name = "organization_id")]
        public uint OrganizationId;
        [DataMember(Name = "poster_identity")]
        public SpacetimeDB.Identity PosterIdentity;
        [DataMember(Name = "content")]
        public string Content;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "duration_seconds")]
        public ulong DurationSeconds;
        [DataMember(Name = "expires_at")]
        public SpacetimeDB.Timestamp ExpiresAt;

        public OrganizationNotice(
            ulong NoticeId,
            uint OrganizationId,
            SpacetimeDB.Identity PosterIdentity,
            string Content,
            SpacetimeDB.Timestamp CreatedAt,
            ulong DurationSeconds,
            SpacetimeDB.Timestamp ExpiresAt
        )
        {
            this.NoticeId = NoticeId;
            this.OrganizationId = OrganizationId;
            this.PosterIdentity = PosterIdentity;
            this.Content = Content;
            this.CreatedAt = CreatedAt;
            this.DurationSeconds = DurationSeconds;
            this.ExpiresAt = ExpiresAt;
        }

        public OrganizationNotice()
        {
            this.Content = "";
        }
    }
}
