// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Organization
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "owner_identity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "owner_display_name")]
        public string OwnerDisplayName;

        public Organization(
            uint Id,
            string Name,
            string Description,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Identity OwnerIdentity,
            string OwnerDisplayName
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.CreatedAt = CreatedAt;
            this.OwnerIdentity = OwnerIdentity;
            this.OwnerDisplayName = OwnerDisplayName;
        }

        public Organization()
        {
            this.Name = "";
            this.Description = "";
            this.OwnerDisplayName = "";
        }
    }
}
