// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OrganizationMember
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "organization_id")]
        public uint OrganizationId;
        [DataMember(Name = "member_identity")]
        public SpacetimeDB.Identity MemberIdentity;

        public OrganizationMember(
            ulong Id,
            uint OrganizationId,
            SpacetimeDB.Identity MemberIdentity
        )
        {
            this.Id = Id;
            this.OrganizationId = OrganizationId;
            this.MemberIdentity = MemberIdentity;
        }

        public OrganizationMember()
        {
        }
    }
}
