// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Protocol
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "content")]
        public string Content;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "edited_at")]
        public SpacetimeDB.Timestamp EditedAt;
        [DataMember(Name = "version")]
        public ulong Version;
        [DataMember(Name = "is_public")]
        public bool IsPublic;

        public Protocol(
            uint Id,
            string Name,
            string Content,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp EditedAt,
            ulong Version,
            bool IsPublic
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Content = Content;
            this.CreatedAt = CreatedAt;
            this.EditedAt = EditedAt;
            this.Version = Version;
            this.IsPublic = IsPublic;
        }

        public Protocol()
        {
            this.Name = "";
            this.Content = "";
        }
    }
}
