// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ProtocolStateEditHistory
    {
        [DataMember(Name = "edit_id")]
        public ulong EditId;
        [DataMember(Name = "protocol_state_id")]
        public uint ProtocolStateId;
        [DataMember(Name = "editor_identity")]
        public SpacetimeDB.Identity EditorIdentity;
        [DataMember(Name = "edited_at")]
        public SpacetimeDB.Timestamp EditedAt;

        public ProtocolStateEditHistory(
            ulong EditId,
            uint ProtocolStateId,
            SpacetimeDB.Identity EditorIdentity,
            SpacetimeDB.Timestamp EditedAt
        )
        {
            this.EditId = EditId;
            this.ProtocolStateId = ProtocolStateId;
            this.EditorIdentity = EditorIdentity;
            this.EditedAt = EditedAt;
        }

        public ProtocolStateEditHistory()
        {
        }
    }
}
