// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ProtocolState
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "protocol_id")]
        public uint ProtocolId;
        [DataMember(Name = "creator_identity")]
        public SpacetimeDB.Identity CreatorIdentity;
        [DataMember(Name = "state")]
        public string State;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "edited_at")]
        public SpacetimeDB.Timestamp EditedAt;

        public ProtocolState(
            uint Id,
            uint ProtocolId,
            SpacetimeDB.Identity CreatorIdentity,
            string State,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp EditedAt
        )
        {
            this.Id = Id;
            this.ProtocolId = ProtocolId;
            this.CreatorIdentity = CreatorIdentity;
            this.State = State;
            this.CreatedAt = CreatedAt;
            this.EditedAt = EditedAt;
        }

        public ProtocolState()
        {
            this.State = "";
        }
    }
}
