// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ProtocolStateOwnership
    {
        [DataMember(Name = "protocol_state_id")]
        public uint ProtocolStateId;
        [DataMember(Name = "owner_identity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "organization_id")]
        public uint OrganizationId;
        [DataMember(Name = "owner_display_name")]
        public string OwnerDisplayName;

        public ProtocolStateOwnership(
            uint ProtocolStateId,
            SpacetimeDB.Identity OwnerIdentity,
            uint OrganizationId,
            string OwnerDisplayName
        )
        {
            this.ProtocolStateId = ProtocolStateId;
            this.OwnerIdentity = OwnerIdentity;
            this.OrganizationId = OrganizationId;
            this.OwnerDisplayName = OwnerDisplayName;
        }

        public ProtocolStateOwnership()
        {
            this.OwnerDisplayName = "";
        }
    }
}
