// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ProtocolEditHistory
    {
        [DataMember(Name = "edit_id")]
        public ulong EditId;
        [DataMember(Name = "protocol_id")]
        public uint ProtocolId;
        [DataMember(Name = "editor_identity")]
        public SpacetimeDB.Identity EditorIdentity;
        [DataMember(Name = "edited_at")]
        public SpacetimeDB.Timestamp EditedAt;
        [DataMember(Name = "version")]
        public ulong Version;
        [DataMember(Name = "previous_content")]
        public string PreviousContent;

        public ProtocolEditHistory(
            ulong EditId,
            uint ProtocolId,
            SpacetimeDB.Identity EditorIdentity,
            SpacetimeDB.Timestamp EditedAt,
            ulong Version,
            string PreviousContent
        )
        {
            this.EditId = EditId;
            this.ProtocolId = ProtocolId;
            this.EditorIdentity = EditorIdentity;
            this.EditedAt = EditedAt;
            this.Version = Version;
            this.PreviousContent = PreviousContent;
        }

        public ProtocolEditHistory()
        {
            this.PreviousContent = "";
        }
    }
}
