// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SavedProtocol
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "user_identity")]
        public SpacetimeDB.Identity UserIdentity;
        [DataMember(Name = "protocol_id")]
        public uint ProtocolId;
        [DataMember(Name = "saved_at")]
        public SpacetimeDB.Timestamp SavedAt;

        public SavedProtocol(
            ulong Id,
            SpacetimeDB.Identity UserIdentity,
            uint ProtocolId,
            SpacetimeDB.Timestamp SavedAt
        )
        {
            this.Id = Id;
            this.UserIdentity = UserIdentity;
            this.ProtocolId = ProtocolId;
            this.SavedAt = SavedAt;
        }

        public SavedProtocol()
        {
        }
    }
}
