// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScheduledTaskAssignee
    {
        [DataMember(Name = "assignment_id")]
        public ulong AssignmentId;
        [DataMember(Name = "task_id")]
        public ulong TaskId;
        [DataMember(Name = "assignee_identity")]
        public SpacetimeDB.Identity AssigneeIdentity;

        public ScheduledTaskAssignee(
            ulong AssignmentId,
            ulong TaskId,
            SpacetimeDB.Identity AssigneeIdentity
        )
        {
            this.AssignmentId = AssignmentId;
            this.TaskId = TaskId;
            this.AssigneeIdentity = AssigneeIdentity;
        }

        public ScheduledTaskAssignee()
        {
        }
    }
}
