// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScheduledProtocolTask
    {
        [DataMember(Name = "task_id")]
        public ulong TaskId;
        [DataMember(Name = "organization_id")]
        public uint OrganizationId;
        [DataMember(Name = "protocol_id")]
        public uint ProtocolId;
        [DataMember(Name = "protocol_state_id")]
        public uint ProtocolStateId;
        [DataMember(Name = "assigner_identity")]
        public SpacetimeDB.Identity AssignerIdentity;
        [DataMember(Name = "start_step")]
        public uint StartStep;
        [DataMember(Name = "end_step")]
        public uint EndStep;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.Timestamp ScheduledAt;
        [DataMember(Name = "due_at")]
        public SpacetimeDB.Timestamp DueAt;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "status")]
        public ScheduledTaskStatus Status;
        [DataMember(Name = "completed_at")]
        public SpacetimeDB.Timestamp? CompletedAt;

        public ScheduledProtocolTask(
            ulong TaskId,
            uint OrganizationId,
            uint ProtocolId,
            uint ProtocolStateId,
            SpacetimeDB.Identity AssignerIdentity,
            uint StartStep,
            uint EndStep,
            SpacetimeDB.Timestamp ScheduledAt,
            SpacetimeDB.Timestamp DueAt,
            SpacetimeDB.Timestamp CreatedAt,
            ScheduledTaskStatus Status,
            SpacetimeDB.Timestamp? CompletedAt
        )
        {
            this.TaskId = TaskId;
            this.OrganizationId = OrganizationId;
            this.ProtocolId = ProtocolId;
            this.ProtocolStateId = ProtocolStateId;
            this.AssignerIdentity = AssignerIdentity;
            this.StartStep = StartStep;
            this.EndStep = EndStep;
            this.ScheduledAt = ScheduledAt;
            this.DueAt = DueAt;
            this.CreatedAt = CreatedAt;
            this.Status = Status;
            this.CompletedAt = CompletedAt;
        }

        public ScheduledProtocolTask()
        {
        }
    }
}
