// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScheduledTaskOverdueTimer
    {
        [DataMember(Name = "timer_id")]
        public ulong TimerId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;

        public ScheduledTaskOverdueTimer(
            ulong TimerId,
            SpacetimeDB.ScheduleAt ScheduledAt
        )
        {
            this.TimerId = TimerId;
            this.ScheduledAt = ScheduledAt;
        }

        public ScheduledTaskOverdueTimer()
        {
            this.ScheduledAt = null!;
        }
    }
}
