// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserProfile
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "last_online")]
        public SpacetimeDB.Timestamp LastOnline;
        [DataMember(Name = "bio")]
        public string Bio;

        public UserProfile(
            SpacetimeDB.Identity Identity,
            string Name,
            bool Online,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp LastOnline,
            string Bio
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Online = Online;
            this.CreatedAt = CreatedAt;
            this.LastOnline = LastOnline;
            this.Bio = Bio;
        }

        public UserProfile()
        {
            this.Name = "";
            this.Bio = "";
        }
    }
}
