// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClientDeviceHandle : RemoteTableHandle<EventContext, ClientDevice>
        {
            protected override string RemoteTableName => "client_device";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ClientDevice row) => row.Identity;

                public IdentityUniqueIndex(ClientDeviceHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal ClientDeviceHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(ClientDevice row) => row.Identity;
        }

        public readonly ClientDeviceHandle ClientDevice;
    }
}
