// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConversationParticipantHandle : RemoteTableHandle<EventContext, ConversationParticipant>
        {
            protected override string RemoteTableName => "conversation_participant";

            public sealed class IdxConversationParticipantIndex : BTreeIndexBase<(ulong ConversationId, SpacetimeDB.Identity ParticipantIdentity)>
            {
                protected override (ulong ConversationId, SpacetimeDB.Identity ParticipantIdentity) GetKey(ConversationParticipant row) => (row.ConversationId, row.ParticipantIdentity);

                public IdxConversationParticipantIndex(ConversationParticipantHandle table) : base(table) { }
            }

            public readonly IdxConversationParticipantIndex IdxConversationParticipant;

            public sealed class ParticipantIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ConversationParticipant row) => row.ParticipantId;

                public ParticipantIdUniqueIndex(ConversationParticipantHandle table) : base(table) { }
            }

            public readonly ParticipantIdUniqueIndex ParticipantId;

            internal ConversationParticipantHandle(DbConnection conn) : base(conn)
            {
                IdxConversationParticipant = new(this);
                ParticipantId = new(this);
            }

            protected override object GetPrimaryKey(ConversationParticipant row) => row.ParticipantId;
        }

        public readonly ConversationParticipantHandle ConversationParticipant;
    }
}
