// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConversationHandle : RemoteTableHandle<EventContext, Conversation>
        {
            protected override string RemoteTableName => "conversation";

            public sealed class ConversationIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Conversation row) => row.ConversationId;

                public ConversationIdUniqueIndex(ConversationHandle table) : base(table) { }
            }

            public readonly ConversationIdUniqueIndex ConversationId;

            public sealed class ParticipantsHashUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Conversation row) => row.ParticipantsHash;

                public ParticipantsHashUniqueIndex(ConversationHandle table) : base(table) { }
            }

            public readonly ParticipantsHashUniqueIndex ParticipantsHash;

            internal ConversationHandle(DbConnection conn) : base(conn)
            {
                ConversationId = new(this);
                ParticipantsHash = new(this);
            }

            protected override object GetPrimaryKey(Conversation row) => row.ConversationId;
        }

        public readonly ConversationHandle Conversation;
    }
}
