// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MediaMetadataHandle : RemoteTableHandle<EventContext, MediaMetadata>
        {
            protected override string RemoteTableName => "media_metadata";

            public sealed class MediaIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MediaMetadata row) => row.MediaId;

                public MediaIdUniqueIndex(MediaMetadataHandle table) : base(table) { }
            }

            public readonly MediaIdUniqueIndex MediaId;

            public sealed class ObjectKeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(MediaMetadata row) => row.ObjectKey;

                public ObjectKeyUniqueIndex(MediaMetadataHandle table) : base(table) { }
            }

            public readonly ObjectKeyUniqueIndex ObjectKey;

            internal MediaMetadataHandle(DbConnection conn) : base(conn)
            {
                MediaId = new(this);
                ObjectKey = new(this);
            }

            protected override object GetPrimaryKey(MediaMetadata row) => row.MediaId;
        }

        public readonly MediaMetadataHandle MediaMetadata;
    }
}
