// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MediaPendingUploadCleanupTimerHandle : RemoteTableHandle<EventContext, MediaPendingUploadCleanupTimer>
        {
            protected override string RemoteTableName => "media_pending_upload_cleanup_timer";

            public sealed class TimerIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MediaPendingUploadCleanupTimer row) => row.TimerId;

                public TimerIdUniqueIndex(MediaPendingUploadCleanupTimerHandle table) : base(table) { }
            }

            public readonly TimerIdUniqueIndex TimerId;

            internal MediaPendingUploadCleanupTimerHandle(DbConnection conn) : base(conn)
            {
                TimerId = new(this);
            }

            protected override object GetPrimaryKey(MediaPendingUploadCleanupTimer row) => row.TimerId;
        }

        public readonly MediaPendingUploadCleanupTimerHandle MediaPendingUploadCleanupTimer;
    }
}
