// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MessageHandle : RemoteTableHandle<EventContext, Message>
        {
            protected override string RemoteTableName => "message";

            public sealed class IdxMessageConversationIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Message row) => row.ConversationId;

                public IdxMessageConversationIndex(MessageHandle table) : base(table) { }
            }

            public readonly IdxMessageConversationIndex IdxMessageConversation;

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Message row) => row.MessageId;

                public MessageIdUniqueIndex(MessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            internal MessageHandle(DbConnection conn) : base(conn)
            {
                IdxMessageConversation = new(this);
                MessageId = new(this);
            }

            protected override object GetPrimaryKey(Message row) => row.MessageId;
        }

        public readonly MessageHandle Message;
    }
}
