// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OrganizationNoticeCleanupTimerHandle : RemoteTableHandle<EventContext, OrganizationNoticeCleanupTimer>
        {
            protected override string RemoteTableName => "organization_notice_cleanup_timer";

            public sealed class TimerIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OrganizationNoticeCleanupTimer row) => row.TimerId;

                public TimerIdUniqueIndex(OrganizationNoticeCleanupTimerHandle table) : base(table) { }
            }

            public readonly TimerIdUniqueIndex TimerId;

            internal OrganizationNoticeCleanupTimerHandle(DbConnection conn) : base(conn)
            {
                TimerId = new(this);
            }

            protected override object GetPrimaryKey(OrganizationNoticeCleanupTimer row) => row.TimerId;
        }

        public readonly OrganizationNoticeCleanupTimerHandle OrganizationNoticeCleanupTimer;
    }
}
