// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OrganizationMemberRequestHandle : RemoteTableHandle<EventContext, OrganizationMemberRequest>
        {
            protected override string RemoteTableName => "organization_member_request";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OrganizationMemberRequest row) => row.Id;

                public IdUniqueIndex(OrganizationMemberRequestHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class OrganizationIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(OrganizationMemberRequest row) => row.OrganizationId;

                public OrganizationIdIndex(OrganizationMemberRequestHandle table) : base(table) { }
            }

            public readonly OrganizationIdIndex OrganizationId;

            public sealed class RequesterIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(OrganizationMemberRequest row) => row.RequesterIdentity;

                public RequesterIdentityIndex(OrganizationMemberRequestHandle table) : base(table) { }
            }

            public readonly RequesterIdentityIndex RequesterIdentity;

            internal OrganizationMemberRequestHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                OrganizationId = new(this);
                RequesterIdentity = new(this);
            }

            protected override object GetPrimaryKey(OrganizationMemberRequest row) => row.Id;
        }

        public readonly OrganizationMemberRequestHandle OrganizationMemberRequest;
    }
}
