// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OrganizationHandle : RemoteTableHandle<EventContext, Organization>
        {
            protected override string RemoteTableName => "organization";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Organization row) => row.Id;

                public IdUniqueIndex(OrganizationHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Organization row) => row.Name;

                public NameUniqueIndex(OrganizationHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            public sealed class OwnerIdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Organization row) => row.OwnerIdentity;

                public OwnerIdentityUniqueIndex(OrganizationHandle table) : base(table) { }
            }

            public readonly OwnerIdentityUniqueIndex OwnerIdentity;

            internal OrganizationHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Name = new(this);
                OwnerIdentity = new(this);
            }

            protected override object GetPrimaryKey(Organization row) => row.Id;
        }

        public readonly OrganizationHandle Organization;
    }
}
