// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OrganizationMemberHandle : RemoteTableHandle<EventContext, OrganizationMember>
        {
            protected override string RemoteTableName => "organization_member";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OrganizationMember row) => row.Id;

                public IdUniqueIndex(OrganizationMemberHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class MemberIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(OrganizationMember row) => row.MemberIdentity;

                public MemberIdentityIndex(OrganizationMemberHandle table) : base(table) { }
            }

            public readonly MemberIdentityIndex MemberIdentity;

            public sealed class OrganizationIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(OrganizationMember row) => row.OrganizationId;

                public OrganizationIdIndex(OrganizationMemberHandle table) : base(table) { }
            }

            public readonly OrganizationIdIndex OrganizationId;

            internal OrganizationMemberHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                MemberIdentity = new(this);
                OrganizationId = new(this);
            }

            protected override object GetPrimaryKey(OrganizationMember row) => row.Id;
        }

        public readonly OrganizationMemberHandle OrganizationMember;
    }
}
