// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProtocolStateHandle : RemoteTableHandle<EventContext, ProtocolState>
        {
            protected override string RemoteTableName => "protocol_state";

            public sealed class CreatorIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ProtocolState row) => row.CreatorIdentity;

                public CreatorIdentityIndex(ProtocolStateHandle table) : base(table) { }
            }

            public readonly CreatorIdentityIndex CreatorIdentity;

            public sealed class EditedAtIndex : BTreeIndexBase<SpacetimeDB.Timestamp>
            {
                protected override SpacetimeDB.Timestamp GetKey(ProtocolState row) => row.EditedAt;

                public EditedAtIndex(ProtocolStateHandle table) : base(table) { }
            }

            public readonly EditedAtIndex EditedAt;

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ProtocolState row) => row.Id;

                public IdUniqueIndex(ProtocolStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ProtocolIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ProtocolState row) => row.ProtocolId;

                public ProtocolIdIndex(ProtocolStateHandle table) : base(table) { }
            }

            public readonly ProtocolIdIndex ProtocolId;

            internal ProtocolStateHandle(DbConnection conn) : base(conn)
            {
                CreatorIdentity = new(this);
                EditedAt = new(this);
                Id = new(this);
                ProtocolId = new(this);
            }

            protected override object GetPrimaryKey(ProtocolState row) => row.Id;
        }

        public readonly ProtocolStateHandle ProtocolState;
    }
}
