// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProtocolStateOwnershipHandle : RemoteTableHandle<EventContext, ProtocolStateOwnership>
        {
            protected override string RemoteTableName => "protocol_state_ownership";

            public sealed class OrganizationIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ProtocolStateOwnership row) => row.OrganizationId;

                public OrganizationIdIndex(ProtocolStateOwnershipHandle table) : base(table) { }
            }

            public readonly OrganizationIdIndex OrganizationId;

            public sealed class OwnerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ProtocolStateOwnership row) => row.OwnerIdentity;

                public OwnerIdentityIndex(ProtocolStateOwnershipHandle table) : base(table) { }
            }

            public readonly OwnerIdentityIndex OwnerIdentity;

            public sealed class ProtocolStateIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ProtocolStateOwnership row) => row.ProtocolStateId;

                public ProtocolStateIdUniqueIndex(ProtocolStateOwnershipHandle table) : base(table) { }
            }

            public readonly ProtocolStateIdUniqueIndex ProtocolStateId;

            internal ProtocolStateOwnershipHandle(DbConnection conn) : base(conn)
            {
                OrganizationId = new(this);
                OwnerIdentity = new(this);
                ProtocolStateId = new(this);
            }

            protected override object GetPrimaryKey(ProtocolStateOwnership row) => row.ProtocolStateId;
        }

        public readonly ProtocolStateOwnershipHandle ProtocolStateOwnership;
    }
}
