// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProtocolOwnershipHandle : RemoteTableHandle<EventContext, ProtocolOwnership>
        {
            protected override string RemoteTableName => "protocol_ownership";

            public sealed class OwnerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ProtocolOwnership row) => row.OwnerIdentity;

                public OwnerIdentityIndex(ProtocolOwnershipHandle table) : base(table) { }
            }

            public readonly OwnerIdentityIndex OwnerIdentity;

            public sealed class ProtocolIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ProtocolOwnership row) => row.ProtocolId;

                public ProtocolIdUniqueIndex(ProtocolOwnershipHandle table) : base(table) { }
            }

            public readonly ProtocolIdUniqueIndex ProtocolId;

            internal ProtocolOwnershipHandle(DbConnection conn) : base(conn)
            {
                OwnerIdentity = new(this);
                ProtocolId = new(this);
            }

            protected override object GetPrimaryKey(ProtocolOwnership row) => row.ProtocolId;
        }

        public readonly ProtocolOwnershipHandle ProtocolOwnership;
    }
}
