// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProtocolStateCleanupTimerHandle : RemoteTableHandle<EventContext, ProtocolStateCleanupTimer>
        {
            protected override string RemoteTableName => "protocol_state_cleanup_timer";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ProtocolStateCleanupTimer row) => row.Id;

                public IdUniqueIndex(ProtocolStateCleanupTimerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ProtocolStateCleanupTimerHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ProtocolStateCleanupTimer row) => row.Id;
        }

        public readonly ProtocolStateCleanupTimerHandle ProtocolStateCleanupTimer;
    }
}
