// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProtocolStateEditHistoryHandle : RemoteTableHandle<EventContext, ProtocolStateEditHistory>
        {
            protected override string RemoteTableName => "protocol_state_edit_history";

            public sealed class EditIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ProtocolStateEditHistory row) => row.EditId;

                public EditIdUniqueIndex(ProtocolStateEditHistoryHandle table) : base(table) { }
            }

            public readonly EditIdUniqueIndex EditId;

            public sealed class EditorIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ProtocolStateEditHistory row) => row.EditorIdentity;

                public EditorIdentityIndex(ProtocolStateEditHistoryHandle table) : base(table) { }
            }

            public readonly EditorIdentityIndex EditorIdentity;

            public sealed class ProtocolStateIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ProtocolStateEditHistory row) => row.ProtocolStateId;

                public ProtocolStateIdIndex(ProtocolStateEditHistoryHandle table) : base(table) { }
            }

            public readonly ProtocolStateIdIndex ProtocolStateId;

            internal ProtocolStateEditHistoryHandle(DbConnection conn) : base(conn)
            {
                EditId = new(this);
                EditorIdentity = new(this);
                ProtocolStateId = new(this);
            }

            protected override object GetPrimaryKey(ProtocolStateEditHistory row) => row.EditId;
        }

        public readonly ProtocolStateEditHistoryHandle ProtocolStateEditHistory;
    }
}
