// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProtocolEditHistoryHandle : RemoteTableHandle<EventContext, ProtocolEditHistory>
        {
            protected override string RemoteTableName => "protocol_edit_history";

            public sealed class EditIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ProtocolEditHistory row) => row.EditId;

                public EditIdUniqueIndex(ProtocolEditHistoryHandle table) : base(table) { }
            }

            public readonly EditIdUniqueIndex EditId;

            public sealed class EditorIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ProtocolEditHistory row) => row.EditorIdentity;

                public EditorIdentityIndex(ProtocolEditHistoryHandle table) : base(table) { }
            }

            public readonly EditorIdentityIndex EditorIdentity;

            public sealed class ProtocolIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ProtocolEditHistory row) => row.ProtocolId;

                public ProtocolIdIndex(ProtocolEditHistoryHandle table) : base(table) { }
            }

            public readonly ProtocolIdIndex ProtocolId;

            internal ProtocolEditHistoryHandle(DbConnection conn) : base(conn)
            {
                EditId = new(this);
                EditorIdentity = new(this);
                ProtocolId = new(this);
            }

            protected override object GetPrimaryKey(ProtocolEditHistory row) => row.EditId;
        }

        public readonly ProtocolEditHistoryHandle ProtocolEditHistory;
    }
}
