// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProtocolHandle : RemoteTableHandle<EventContext, Protocol>
        {
            protected override string RemoteTableName => "protocol";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Protocol row) => row.Id;

                public IdUniqueIndex(ProtocolHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ProtocolHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Protocol row) => row.Id;
        }

        public readonly ProtocolHandle Protocol;
    }
}
