// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SavedProtocolHandle : RemoteTableHandle<EventContext, SavedProtocol>
        {
            protected override string RemoteTableName => "saved_protocol";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SavedProtocol row) => row.Id;

                public IdUniqueIndex(SavedProtocolHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ProtocolIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(SavedProtocol row) => row.ProtocolId;

                public ProtocolIdIndex(SavedProtocolHandle table) : base(table) { }
            }

            public readonly ProtocolIdIndex ProtocolId;

            public sealed class UserIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(SavedProtocol row) => row.UserIdentity;

                public UserIdentityIndex(SavedProtocolHandle table) : base(table) { }
            }

            public readonly UserIdentityIndex UserIdentity;

            internal SavedProtocolHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ProtocolId = new(this);
                UserIdentity = new(this);
            }

            protected override object GetPrimaryKey(SavedProtocol row) => row.Id;
        }

        public readonly SavedProtocolHandle SavedProtocol;
    }
}
