// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ScheduledTaskOverdueTimerHandle : RemoteTableHandle<EventContext, ScheduledTaskOverdueTimer>
        {
            protected override string RemoteTableName => "scheduled_task_overdue_timer";

            public sealed class TimerIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ScheduledTaskOverdueTimer row) => row.TimerId;

                public TimerIdUniqueIndex(ScheduledTaskOverdueTimerHandle table) : base(table) { }
            }

            public readonly TimerIdUniqueIndex TimerId;

            internal ScheduledTaskOverdueTimerHandle(DbConnection conn) : base(conn)
            {
                TimerId = new(this);
            }

            protected override object GetPrimaryKey(ScheduledTaskOverdueTimer row) => row.TimerId;
        }

        public readonly ScheduledTaskOverdueTimerHandle ScheduledTaskOverdueTimer;
    }
}
