// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ScheduledTaskAssigneeHandle : RemoteTableHandle<EventContext, ScheduledTaskAssignee>
        {
            protected override string RemoteTableName => "scheduled_task_assignee";

            public sealed class AssigneeIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ScheduledTaskAssignee row) => row.AssigneeIdentity;

                public AssigneeIdentityIndex(ScheduledTaskAssigneeHandle table) : base(table) { }
            }

            public readonly AssigneeIdentityIndex AssigneeIdentity;

            public sealed class AssignmentIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ScheduledTaskAssignee row) => row.AssignmentId;

                public AssignmentIdUniqueIndex(ScheduledTaskAssigneeHandle table) : base(table) { }
            }

            public readonly AssignmentIdUniqueIndex AssignmentId;

            public sealed class TaskIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ScheduledTaskAssignee row) => row.TaskId;

                public TaskIdIndex(ScheduledTaskAssigneeHandle table) : base(table) { }
            }

            public readonly TaskIdIndex TaskId;

            internal ScheduledTaskAssigneeHandle(DbConnection conn) : base(conn)
            {
                AssigneeIdentity = new(this);
                AssignmentId = new(this);
                TaskId = new(this);
            }

            protected override object GetPrimaryKey(ScheduledTaskAssignee row) => row.AssignmentId;
        }

        public readonly ScheduledTaskAssigneeHandle ScheduledTaskAssignee;
    }
}
