// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ScheduledProtocolTaskHandle : RemoteTableHandle<EventContext, ScheduledProtocolTask>
        {
            protected override string RemoteTableName => "scheduled_protocol_task";

            public sealed class AssignerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ScheduledProtocolTask row) => row.AssignerIdentity;

                public AssignerIdentityIndex(ScheduledProtocolTaskHandle table) : base(table) { }
            }

            public readonly AssignerIdentityIndex AssignerIdentity;

            public sealed class DueAtIndex : BTreeIndexBase<SpacetimeDB.Timestamp>
            {
                protected override SpacetimeDB.Timestamp GetKey(ScheduledProtocolTask row) => row.DueAt;

                public DueAtIndex(ScheduledProtocolTaskHandle table) : base(table) { }
            }

            public readonly DueAtIndex DueAt;

            public sealed class OrganizationIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ScheduledProtocolTask row) => row.OrganizationId;

                public OrganizationIdIndex(ScheduledProtocolTaskHandle table) : base(table) { }
            }

            public readonly OrganizationIdIndex OrganizationId;

            public sealed class ProtocolIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ScheduledProtocolTask row) => row.ProtocolId;

                public ProtocolIdIndex(ScheduledProtocolTaskHandle table) : base(table) { }
            }

            public readonly ProtocolIdIndex ProtocolId;

            public sealed class ProtocolStateIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ScheduledProtocolTask row) => row.ProtocolStateId;

                public ProtocolStateIdIndex(ScheduledProtocolTaskHandle table) : base(table) { }
            }

            public readonly ProtocolStateIdIndex ProtocolStateId;

            public sealed class TaskIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ScheduledProtocolTask row) => row.TaskId;

                public TaskIdUniqueIndex(ScheduledProtocolTaskHandle table) : base(table) { }
            }

            public readonly TaskIdUniqueIndex TaskId;

            internal ScheduledProtocolTaskHandle(DbConnection conn) : base(conn)
            {
                AssignerIdentity = new(this);
                DueAt = new(this);
                OrganizationId = new(this);
                ProtocolId = new(this);
                ProtocolStateId = new(this);
                TaskId = new(this);
            }

            protected override object GetPrimaryKey(ScheduledProtocolTask row) => row.TaskId;
        }

        public readonly ScheduledProtocolTaskHandle ScheduledProtocolTask;
    }
}
