// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserProfileHandle : RemoteTableHandle<EventContext, UserProfile>
        {
            protected override string RemoteTableName => "user_profile";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserProfile row) => row.Identity;

                public IdentityUniqueIndex(UserProfileHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UserProfileHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(UserProfile row) => row.Identity;
        }

        public readonly UserProfileHandle UserProfile;
    }
}
