// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        internal RemoteReducers(DbConnection conn, SetReducerFlags flags) : base(conn) => SetCallReducerFlags = flags;
        internal readonly SetReducerFlags SetCallReducerFlags;
    }

    public sealed partial class RemoteTables : RemoteTablesBase
    {
        public RemoteTables(DbConnection conn)
        {
            AddTable(ClientDevice = new(conn));
            AddTable(MediaMetadata = new(conn));
            AddTable(MediaPendingUploadCleanupTimer = new(conn));
            AddTable(Organization = new(conn));
            AddTable(OrganizationMember = new(conn));
            AddTable(OrganizationMemberRequest = new(conn));
            AddTable(OrganizationNotice = new(conn));
            AddTable(OrganizationNoticeCleanupTimer = new(conn));
            AddTable(Protocol = new(conn));
            AddTable(ProtocolEditHistory = new(conn));
            AddTable(ProtocolOwnership = new(conn));
            AddTable(ProtocolState = new(conn));
            AddTable(ProtocolStateCleanupTimer = new(conn));
            AddTable(ProtocolStateEditHistory = new(conn));
            AddTable(ProtocolStateOwnership = new(conn));
            AddTable(SavedProtocol = new(conn));
            AddTable(ScheduledProtocolTask = new(conn));
            AddTable(ScheduledTaskAssignee = new(conn));
            AddTable(ScheduledTaskOverdueTimer = new(conn));
            AddTable(UserProfile = new(conn));
        }
    }

    public sealed partial class SetReducerFlags { }

    public interface IRemoteDbContext : IDbContext<RemoteTables, RemoteReducers, SetReducerFlags, SubscriptionBuilder> { }

    public sealed class EventContext : IEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;

        /// <summary>
        /// The event that caused this callback to run.
        /// </summary>
        public readonly Event<Reducer> Event;

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to setters for per-reducer flags.
        ///
        /// The returned <c>SetReducerFlags</c> will have a method to invoke,
        /// for each reducer defined by the module,
        /// which call-flags for the reducer can be set.
        /// </summary>
        public SetReducerFlags SetReducerFlags => conn.SetReducerFlags;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;

        internal EventContext(DbConnection conn, Event<Reducer> Event)
        {
            this.conn = conn;
            this.Event = Event;
        }
    }

    public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        /// <summary>
        /// The reducer event that caused this callback to run.
        /// </summary>
        public readonly ReducerEvent<Reducer> Event;

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to setters for per-reducer flags.
        ///
        /// The returned <c>SetReducerFlags</c> will have a method to invoke,
        /// for each reducer defined by the module,
        /// which call-flags for the reducer can be set.
        /// </summary>
        public SetReducerFlags SetReducerFlags => conn.SetReducerFlags;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;

        internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
        {
            this.conn = conn;
            Event = reducerEvent;
        }
    }

    public sealed class ErrorContext : IErrorContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        /// <summary>
        /// The <c>Exception</c> that caused this error callback to be run.
        /// </summary>
        public readonly Exception Event;
        Exception IErrorContext.Event
        {
            get
            {
                return Event;
            }
        }

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to setters for per-reducer flags.
        ///
        /// The returned <c>SetReducerFlags</c> will have a method to invoke,
        /// for each reducer defined by the module,
        /// which call-flags for the reducer can be set.
        /// </summary>
        public SetReducerFlags SetReducerFlags => conn.SetReducerFlags;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;

        internal ErrorContext(DbConnection conn, Exception error)
        {
            this.conn = conn;
            Event = error;
        }
    }

    public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to setters for per-reducer flags.
        ///
        /// The returned <c>SetReducerFlags</c> will have a method to invoke,
        /// for each reducer defined by the module,
        /// which call-flags for the reducer can be set.
        /// </summary>
        public SetReducerFlags SetReducerFlags => conn.SetReducerFlags;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;

        internal SubscriptionEventContext(DbConnection conn)
        {
            this.conn = conn;
        }
    }

    /// <summary>
    /// Builder-pattern constructor for subscription queries.
    /// </summary>
    public sealed class SubscriptionBuilder
    {
        private readonly IDbConnection conn;

        private event Action<SubscriptionEventContext>? Applied;
        private event Action<ErrorContext, Exception>? Error;

        /// <summary>
        /// Private API, use <c>conn.SubscriptionBuilder()</c> instead.
        /// </summary>
        public SubscriptionBuilder(IDbConnection conn)
        {
            this.conn = conn;
        }

        /// <summary>
        /// Register a callback to run when the subscription is applied.
        /// </summary>
        public SubscriptionBuilder OnApplied(
            Action<SubscriptionEventContext> callback
        )
        {
            Applied += callback;
            return this;
        }

        /// <summary>
        /// Register a callback to run when the subscription fails.
        ///
        /// Note that this callback may run either when attempting to apply the subscription,
        /// in which case <c>Self::on_applied</c> will never run,
        /// or later during the subscription's lifetime if the module's interface changes,
        /// in which case <c>Self::on_applied</c> may have already run.
        /// </summary>
        public SubscriptionBuilder OnError(
            Action<ErrorContext, Exception> callback
        )
        {
            Error += callback;
            return this;
        }

        /// <summary>
        /// Subscribe to the following SQL queries.
        /// 
        /// This method returns immediately, with the data not yet added to the DbConnection.
        /// The provided callbacks will be invoked once the data is returned from the remote server.
        /// Data from all the provided queries will be returned at the same time.
        /// 
        /// See the SpacetimeDB SQL docs for more information on SQL syntax:
        /// <a href="https://spacetimedb.com/docs/sql">https://spacetimedb.com/docs/sql</a>
        /// </summary>
        public SubscriptionHandle Subscribe(
            string[] querySqls
        ) => new(conn, Applied, Error, querySqls);

        /// <summary>
        /// Subscribe to all rows from all tables.
        ///
        /// This method is intended as a convenience
        /// for applications where client-side memory use and network bandwidth are not concerns.
        /// Applications where these resources are a constraint
        /// should register more precise queries via <c>Self.Subscribe</c>
        /// in order to replicate only the subset of data which the client needs to function.
        ///
        /// This method should not be combined with <c>Self.Subscribe</c> on the same <c>DbConnection</c>.
        /// A connection may either <c>Self.Subscribe</c> to particular queries,
        /// or <c>Self.SubscribeToAllTables</c>, but not both.
        /// Attempting to call <c>Self.Subscribe</c>
        /// on a <c>DbConnection</c> that has previously used <c>Self.SubscribeToAllTables</c>,
        /// or vice versa, may misbehave in any number of ways,
        /// including dropping subscriptions, corrupting the client cache, or panicking.
        /// </summary>
        public void SubscribeToAllTables()
        {
            // Make sure we use the legacy handle constructor here, even though there's only 1 query.
            // We drop the error handler, since it can't be called for legacy subscriptions.
            new SubscriptionHandle(
                conn,
                Applied,
                new string[] { "SELECT * FROM *" }
            );
        }
    }

    public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext>
    {
        /// <summary>
        /// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
        /// </summary>
        public SubscriptionHandle(IDbConnection conn, Action<SubscriptionEventContext>? onApplied, string[] querySqls) : base(conn, onApplied, querySqls)
        { }

        /// <summary>
        /// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
        /// </summary>
        public SubscriptionHandle(
            IDbConnection conn,
            Action<SubscriptionEventContext>? onApplied,
            Action<ErrorContext, Exception>? onError,
            string[] querySqls
        ) : base(conn, onApplied, onError, querySqls)
        { }
    }

    public abstract partial class Reducer
    {
        private Reducer() { }
    }

    public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
    {
        public override RemoteTables Db { get; }
        public readonly RemoteReducers Reducers;
        public readonly SetReducerFlags SetReducerFlags = new();

        public DbConnection()
        {
            Db = new(this);
            Reducers = new(this, SetReducerFlags);
        }

        protected override Reducer ToReducer(TransactionUpdate update)
        {
            var encodedArgs = update.ReducerCall.Args;
            return update.ReducerCall.ReducerName switch
            {
                "check_overdue_protocol_tasks" => BSATNHelpers.Decode<Reducer.CheckOverdueProtocolTasks>(encodedArgs),
                "cleanup_old_protocol_states" => BSATNHelpers.Decode<Reducer.CleanupOldProtocolStates>(encodedArgs),
                "cleanup_stale_media_pending_uploads" => BSATNHelpers.Decode<Reducer.CleanupStaleMediaPendingUploads>(encodedArgs),
                "client_connected" => BSATNHelpers.Decode<Reducer.ClientConnected>(encodedArgs),
                "client_disconnected" => BSATNHelpers.Decode<Reducer.ClientDisconnected>(encodedArgs),
                "confirm_media_upload_complete" => BSATNHelpers.Decode<Reducer.ConfirmMediaUploadComplete>(encodedArgs),
                "delete_media_metadata" => BSATNHelpers.Decode<Reducer.DeleteMediaMetadata>(encodedArgs),
                "register_profile" => BSATNHelpers.Decode<Reducer.RegisterProfile>(encodedArgs),
                "request_join_organization" => BSATNHelpers.Decode<Reducer.RequestJoinOrganization>(encodedArgs),
                "request_media_upload_slot" => BSATNHelpers.Decode<Reducer.RequestMediaUploadSlot>(encodedArgs),
                "run_organization_notice_cleanup" => BSATNHelpers.Decode<Reducer.RunOrganizationNoticeCleanup>(encodedArgs),
                "try_approve_organization_member_request" => BSATNHelpers.Decode<Reducer.TryApproveOrganizationMemberRequest>(encodedArgs),
                "try_cancel_scheduled_task" => BSATNHelpers.Decode<Reducer.TryCancelScheduledTask>(encodedArgs),
                "try_complete_scheduled_task" => BSATNHelpers.Decode<Reducer.TryCompleteScheduledTask>(encodedArgs),
                "try_create_organization" => BSATNHelpers.Decode<Reducer.TryCreateOrganization>(encodedArgs),
                "try_create_protocol" => BSATNHelpers.Decode<Reducer.TryCreateProtocol>(encodedArgs),
                "try_create_protocol_state" => BSATNHelpers.Decode<Reducer.TryCreateProtocolState>(encodedArgs),
                "try_delete_organization" => BSATNHelpers.Decode<Reducer.TryDeleteOrganization>(encodedArgs),
                "try_delete_organization_notice" => BSATNHelpers.Decode<Reducer.TryDeleteOrganizationNotice>(encodedArgs),
                "try_delete_protocol" => BSATNHelpers.Decode<Reducer.TryDeleteProtocol>(encodedArgs),
                "try_delete_protocol_state" => BSATNHelpers.Decode<Reducer.TryDeleteProtocolState>(encodedArgs),
                "try_deny_organization_member_request" => BSATNHelpers.Decode<Reducer.TryDenyOrganizationMemberRequest>(encodedArgs),
                "try_edit_protocol" => BSATNHelpers.Decode<Reducer.TryEditProtocol>(encodedArgs),
                "try_edit_protocol_state" => BSATNHelpers.Decode<Reducer.TryEditProtocolState>(encodedArgs),
                "try_fork_protocol" => BSATNHelpers.Decode<Reducer.TryForkProtocol>(encodedArgs),
                "try_leave_organization" => BSATNHelpers.Decode<Reducer.TryLeaveOrganization>(encodedArgs),
                "try_post_organization_notice" => BSATNHelpers.Decode<Reducer.TryPostOrganizationNotice>(encodedArgs),
                "try_rollback_protocol" => BSATNHelpers.Decode<Reducer.TryRollbackProtocol>(encodedArgs),
                "try_save_protocol" => BSATNHelpers.Decode<Reducer.TrySaveProtocol>(encodedArgs),
                "try_schedule_protocol_task" => BSATNHelpers.Decode<Reducer.TryScheduleProtocolTask>(encodedArgs),
                "try_start_scheduled_task" => BSATNHelpers.Decode<Reducer.TryStartScheduledTask>(encodedArgs),
                "try_unsave_protocol" => BSATNHelpers.Decode<Reducer.TryUnsaveProtocol>(encodedArgs),
                "update_organization_name" => BSATNHelpers.Decode<Reducer.UpdateOrganizationName>(encodedArgs),
                "update_user_profile_name" => BSATNHelpers.Decode<Reducer.UpdateUserProfileName>(encodedArgs),
                var reducer => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        protected override IEventContext ToEventContext(Event<Reducer> Event) =>
        new EventContext(this, Event);

        protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) =>
        new ReducerEventContext(this, reducerEvent);

        protected override ISubscriptionEventContext MakeSubscriptionEventContext() =>
        new SubscriptionEventContext(this);

        protected override IErrorContext ToErrorContext(Exception exception) =>
        new ErrorContext(this, exception);

        protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
        {
            var eventContext = (ReducerEventContext)context;
            return reducer switch
            {
                Reducer.CheckOverdueProtocolTasks args => Reducers.InvokeCheckOverdueProtocolTasks(eventContext, args),
                Reducer.CleanupOldProtocolStates args => Reducers.InvokeCleanupOldProtocolStates(eventContext, args),
                Reducer.CleanupStaleMediaPendingUploads args => Reducers.InvokeCleanupStaleMediaPendingUploads(eventContext, args),
                Reducer.ClientConnected args => Reducers.InvokeClientConnected(eventContext, args),
                Reducer.ClientDisconnected args => Reducers.InvokeClientDisconnected(eventContext, args),
                Reducer.ConfirmMediaUploadComplete args => Reducers.InvokeConfirmMediaUploadComplete(eventContext, args),
                Reducer.DeleteMediaMetadata args => Reducers.InvokeDeleteMediaMetadata(eventContext, args),
                Reducer.RegisterProfile args => Reducers.InvokeRegisterProfile(eventContext, args),
                Reducer.RequestJoinOrganization args => Reducers.InvokeRequestJoinOrganization(eventContext, args),
                Reducer.RequestMediaUploadSlot args => Reducers.InvokeRequestMediaUploadSlot(eventContext, args),
                Reducer.RunOrganizationNoticeCleanup args => Reducers.InvokeRunOrganizationNoticeCleanup(eventContext, args),
                Reducer.TryApproveOrganizationMemberRequest args => Reducers.InvokeTryApproveOrganizationMemberRequest(eventContext, args),
                Reducer.TryCancelScheduledTask args => Reducers.InvokeTryCancelScheduledTask(eventContext, args),
                Reducer.TryCompleteScheduledTask args => Reducers.InvokeTryCompleteScheduledTask(eventContext, args),
                Reducer.TryCreateOrganization args => Reducers.InvokeTryCreateOrganization(eventContext, args),
                Reducer.TryCreateProtocol args => Reducers.InvokeTryCreateProtocol(eventContext, args),
                Reducer.TryCreateProtocolState args => Reducers.InvokeTryCreateProtocolState(eventContext, args),
                Reducer.TryDeleteOrganization args => Reducers.InvokeTryDeleteOrganization(eventContext, args),
                Reducer.TryDeleteOrganizationNotice args => Reducers.InvokeTryDeleteOrganizationNotice(eventContext, args),
                Reducer.TryDeleteProtocol args => Reducers.InvokeTryDeleteProtocol(eventContext, args),
                Reducer.TryDeleteProtocolState args => Reducers.InvokeTryDeleteProtocolState(eventContext, args),
                Reducer.TryDenyOrganizationMemberRequest args => Reducers.InvokeTryDenyOrganizationMemberRequest(eventContext, args),
                Reducer.TryEditProtocol args => Reducers.InvokeTryEditProtocol(eventContext, args),
                Reducer.TryEditProtocolState args => Reducers.InvokeTryEditProtocolState(eventContext, args),
                Reducer.TryForkProtocol args => Reducers.InvokeTryForkProtocol(eventContext, args),
                Reducer.TryLeaveOrganization args => Reducers.InvokeTryLeaveOrganization(eventContext, args),
                Reducer.TryPostOrganizationNotice args => Reducers.InvokeTryPostOrganizationNotice(eventContext, args),
                Reducer.TryRollbackProtocol args => Reducers.InvokeTryRollbackProtocol(eventContext, args),
                Reducer.TrySaveProtocol args => Reducers.InvokeTrySaveProtocol(eventContext, args),
                Reducer.TryScheduleProtocolTask args => Reducers.InvokeTryScheduleProtocolTask(eventContext, args),
                Reducer.TryStartScheduledTask args => Reducers.InvokeTryStartScheduledTask(eventContext, args),
                Reducer.TryUnsaveProtocol args => Reducers.InvokeTryUnsaveProtocol(eventContext, args),
                Reducer.UpdateOrganizationName args => Reducers.InvokeUpdateOrganizationName(eventContext, args),
                Reducer.UpdateUserProfileName args => Reducers.InvokeUpdateUserProfileName(eventContext, args),
                _ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        public SubscriptionBuilder SubscriptionBuilder() => new(this);
    }
}
