// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddUserToConversationHandler(ReducerEventContext ctx, ulong conversationId, SpacetimeDB.Identity userToAdd);
        public event AddUserToConversationHandler? OnAddUserToConversation;

        public void AddUserToConversation(ulong conversationId, SpacetimeDB.Identity userToAdd)
        {
            conn.InternalCallReducer(new Reducer.AddUserToConversation(conversationId, userToAdd), this.SetCallReducerFlags.AddUserToConversationFlags);
        }

        public bool InvokeAddUserToConversation(ReducerEventContext ctx, Reducer.AddUserToConversation args)
        {
            if (OnAddUserToConversation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddUserToConversation(
                ctx,
                args.ConversationId,
                args.UserToAdd
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddUserToConversation : Reducer, IReducerArgs
        {
            [DataMember(Name = "conversation_id")]
            public ulong ConversationId;
            [DataMember(Name = "user_to_add")]
            public SpacetimeDB.Identity UserToAdd;

            public AddUserToConversation(
                ulong ConversationId,
                SpacetimeDB.Identity UserToAdd
            )
            {
                this.ConversationId = ConversationId;
                this.UserToAdd = UserToAdd;
            }

            public AddUserToConversation()
            {
            }

            string IReducerArgs.ReducerName => "add_user_to_conversation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddUserToConversationFlags;
        public void AddUserToConversation(CallReducerFlags flags) => AddUserToConversationFlags = flags;
    }
}
