// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheckOverdueProtocolTasksHandler(ReducerEventContext ctx, ScheduledTaskOverdueTimer timer);
        public event CheckOverdueProtocolTasksHandler? OnCheckOverdueProtocolTasks;

        public void CheckOverdueProtocolTasks(ScheduledTaskOverdueTimer timer)
        {
            conn.InternalCallReducer(new Reducer.CheckOverdueProtocolTasks(timer), this.SetCallReducerFlags.CheckOverdueProtocolTasksFlags);
        }

        public bool InvokeCheckOverdueProtocolTasks(ReducerEventContext ctx, Reducer.CheckOverdueProtocolTasks args)
        {
            if (OnCheckOverdueProtocolTasks == null) return false;
            OnCheckOverdueProtocolTasks(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheckOverdueProtocolTasks : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public ScheduledTaskOverdueTimer Timer;

            public CheckOverdueProtocolTasks(ScheduledTaskOverdueTimer Timer)
            {
                this.Timer = Timer;
            }

            public CheckOverdueProtocolTasks()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "check_overdue_protocol_tasks";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheckOverdueProtocolTasksFlags;
        public void CheckOverdueProtocolTasks(CallReducerFlags flags) => CheckOverdueProtocolTasksFlags = flags;
    }
}
