// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CleanupOldProtocolStatesHandler(ReducerEventContext ctx, ProtocolStateCleanupTimer scheduleArgs);
        public event CleanupOldProtocolStatesHandler? OnCleanupOldProtocolStates;

        public void CleanupOldProtocolStates(ProtocolStateCleanupTimer scheduleArgs)
        {
            conn.InternalCallReducer(new Reducer.CleanupOldProtocolStates(scheduleArgs), this.SetCallReducerFlags.CleanupOldProtocolStatesFlags);
        }

        public bool InvokeCleanupOldProtocolStates(ReducerEventContext ctx, Reducer.CleanupOldProtocolStates args)
        {
            if (OnCleanupOldProtocolStates == null) return false;
            OnCleanupOldProtocolStates(
                ctx,
                args.ScheduleArgs
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CleanupOldProtocolStates : Reducer, IReducerArgs
        {
            [DataMember(Name = "_schedule_args")]
            public ProtocolStateCleanupTimer ScheduleArgs;

            public CleanupOldProtocolStates(ProtocolStateCleanupTimer ScheduleArgs)
            {
                this.ScheduleArgs = ScheduleArgs;
            }

            public CleanupOldProtocolStates()
            {
                this.ScheduleArgs = new();
            }

            string IReducerArgs.ReducerName => "cleanup_old_protocol_states";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CleanupOldProtocolStatesFlags;
        public void CleanupOldProtocolStates(CallReducerFlags flags) => CleanupOldProtocolStatesFlags = flags;
    }
}
