// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CleanupStaleMediaPendingUploadsHandler(ReducerEventContext ctx, MediaPendingUploadCleanupTimer timer);
        public event CleanupStaleMediaPendingUploadsHandler? OnCleanupStaleMediaPendingUploads;

        public void CleanupStaleMediaPendingUploads(MediaPendingUploadCleanupTimer timer)
        {
            conn.InternalCallReducer(new Reducer.CleanupStaleMediaPendingUploads(timer), this.SetCallReducerFlags.CleanupStaleMediaPendingUploadsFlags);
        }

        public bool InvokeCleanupStaleMediaPendingUploads(ReducerEventContext ctx, Reducer.CleanupStaleMediaPendingUploads args)
        {
            if (OnCleanupStaleMediaPendingUploads == null) return false;
            OnCleanupStaleMediaPendingUploads(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CleanupStaleMediaPendingUploads : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public MediaPendingUploadCleanupTimer Timer;

            public CleanupStaleMediaPendingUploads(MediaPendingUploadCleanupTimer Timer)
            {
                this.Timer = Timer;
            }

            public CleanupStaleMediaPendingUploads()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "cleanup_stale_media_pending_uploads";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CleanupStaleMediaPendingUploadsFlags;
        public void CleanupStaleMediaPendingUploads(CallReducerFlags flags) => CleanupStaleMediaPendingUploadsFlags = flags;
    }
}
