// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ConfirmMediaUploadCompleteHandler(ReducerEventContext ctx, string objectKey, ulong fileSize);
        public event ConfirmMediaUploadCompleteHandler? OnConfirmMediaUploadComplete;

        public void ConfirmMediaUploadComplete(string objectKey, ulong fileSize)
        {
            conn.InternalCallReducer(new Reducer.ConfirmMediaUploadComplete(objectKey, fileSize), this.SetCallReducerFlags.ConfirmMediaUploadCompleteFlags);
        }

        public bool InvokeConfirmMediaUploadComplete(ReducerEventContext ctx, Reducer.ConfirmMediaUploadComplete args)
        {
            if (OnConfirmMediaUploadComplete == null) return false;
            OnConfirmMediaUploadComplete(
                ctx,
                args.ObjectKey,
                args.FileSize
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ConfirmMediaUploadComplete : Reducer, IReducerArgs
        {
            [DataMember(Name = "object_key")]
            public string ObjectKey;
            [DataMember(Name = "file_size")]
            public ulong FileSize;

            public ConfirmMediaUploadComplete(
                string ObjectKey,
                ulong FileSize
            )
            {
                this.ObjectKey = ObjectKey;
                this.FileSize = FileSize;
            }

            public ConfirmMediaUploadComplete()
            {
                this.ObjectKey = "";
            }

            string IReducerArgs.ReducerName => "confirm_media_upload_complete";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ConfirmMediaUploadCompleteFlags;
        public void ConfirmMediaUploadComplete(CallReducerFlags flags) => ConfirmMediaUploadCompleteFlags = flags;
    }
}
