// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteMediaMetadataHandler(ReducerEventContext ctx, string objectKey);
        public event DeleteMediaMetadataHandler? OnDeleteMediaMetadata;

        public void DeleteMediaMetadata(string objectKey)
        {
            conn.InternalCallReducer(new Reducer.DeleteMediaMetadata(objectKey), this.SetCallReducerFlags.DeleteMediaMetadataFlags);
        }

        public bool InvokeDeleteMediaMetadata(ReducerEventContext ctx, Reducer.DeleteMediaMetadata args)
        {
            if (OnDeleteMediaMetadata == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteMediaMetadata(
                ctx,
                args.ObjectKey
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteMediaMetadata : Reducer, IReducerArgs
        {
            [DataMember(Name = "object_key")]
            public string ObjectKey;

            public DeleteMediaMetadata(string ObjectKey)
            {
                this.ObjectKey = ObjectKey;
            }

            public DeleteMediaMetadata()
            {
                this.ObjectKey = "";
            }

            string IReducerArgs.ReducerName => "delete_media_metadata";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteMediaMetadataFlags;
        public void DeleteMediaMetadata(CallReducerFlags flags) => DeleteMediaMetadataFlags = flags;
    }
}
