// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LeaveConversationHandler(ReducerEventContext ctx, ulong conversationId);
        public event LeaveConversationHandler? OnLeaveConversation;

        public void LeaveConversation(ulong conversationId)
        {
            conn.InternalCallReducer(new Reducer.LeaveConversation(conversationId), this.SetCallReducerFlags.LeaveConversationFlags);
        }

        public bool InvokeLeaveConversation(ReducerEventContext ctx, Reducer.LeaveConversation args)
        {
            if (OnLeaveConversation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLeaveConversation(
                ctx,
                args.ConversationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LeaveConversation : Reducer, IReducerArgs
        {
            [DataMember(Name = "conversation_id")]
            public ulong ConversationId;

            public LeaveConversation(ulong ConversationId)
            {
                this.ConversationId = ConversationId;
            }

            public LeaveConversation()
            {
            }

            string IReducerArgs.ReducerName => "leave_conversation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LeaveConversationFlags;
        public void LeaveConversation(CallReducerFlags flags) => LeaveConversationFlags = flags;
    }
}
