// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterProfileHandler(ReducerEventContext ctx, string name);
        public event RegisterProfileHandler? OnRegisterProfile;

        public void RegisterProfile(string name)
        {
            conn.InternalCallReducer(new Reducer.RegisterProfile(name), this.SetCallReducerFlags.RegisterProfileFlags);
        }

        public bool InvokeRegisterProfile(ReducerEventContext ctx, Reducer.RegisterProfile args)
        {
            if (OnRegisterProfile == null) return false;
            OnRegisterProfile(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public RegisterProfile(string Name)
            {
                this.Name = Name;
            }

            public RegisterProfile()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "register_profile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterProfileFlags;
        public void RegisterProfile(CallReducerFlags flags) => RegisterProfileFlags = flags;
    }
}
