// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RenameConversationHandler(ReducerEventContext ctx, ulong conversationId, string newName);
        public event RenameConversationHandler? OnRenameConversation;

        public void RenameConversation(ulong conversationId, string newName)
        {
            conn.InternalCallReducer(new Reducer.RenameConversation(conversationId, newName), this.SetCallReducerFlags.RenameConversationFlags);
        }

        public bool InvokeRenameConversation(ReducerEventContext ctx, Reducer.RenameConversation args)
        {
            if (OnRenameConversation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRenameConversation(
                ctx,
                args.ConversationId,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RenameConversation : Reducer, IReducerArgs
        {
            [DataMember(Name = "conversation_id")]
            public ulong ConversationId;
            [DataMember(Name = "new_name")]
            public string NewName;

            public RenameConversation(
                ulong ConversationId,
                string NewName
            )
            {
                this.ConversationId = ConversationId;
                this.NewName = NewName;
            }

            public RenameConversation()
            {
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "rename_conversation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RenameConversationFlags;
        public void RenameConversation(CallReducerFlags flags) => RenameConversationFlags = flags;
    }
}
