// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestJoinOrganizationHandler(ReducerEventContext ctx, uint organizationId);
        public event RequestJoinOrganizationHandler? OnRequestJoinOrganization;

        public void RequestJoinOrganization(uint organizationId)
        {
            conn.InternalCallReducer(new Reducer.RequestJoinOrganization(organizationId), this.SetCallReducerFlags.RequestJoinOrganizationFlags);
        }

        public bool InvokeRequestJoinOrganization(ReducerEventContext ctx, Reducer.RequestJoinOrganization args)
        {
            if (OnRequestJoinOrganization == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestJoinOrganization(
                ctx,
                args.OrganizationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestJoinOrganization : Reducer, IReducerArgs
        {
            [DataMember(Name = "organization_id")]
            public uint OrganizationId;

            public RequestJoinOrganization(uint OrganizationId)
            {
                this.OrganizationId = OrganizationId;
            }

            public RequestJoinOrganization()
            {
            }

            string IReducerArgs.ReducerName => "request_join_organization";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RequestJoinOrganizationFlags;
        public void RequestJoinOrganization(CallReducerFlags flags) => RequestJoinOrganizationFlags = flags;
    }
}
