// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestMediaUploadSlotHandler(ReducerEventContext ctx, string objectKey, string originalFilename, string contentType);
        public event RequestMediaUploadSlotHandler? OnRequestMediaUploadSlot;

        public void RequestMediaUploadSlot(string objectKey, string originalFilename, string contentType)
        {
            conn.InternalCallReducer(new Reducer.RequestMediaUploadSlot(objectKey, originalFilename, contentType), this.SetCallReducerFlags.RequestMediaUploadSlotFlags);
        }

        public bool InvokeRequestMediaUploadSlot(ReducerEventContext ctx, Reducer.RequestMediaUploadSlot args)
        {
            if (OnRequestMediaUploadSlot == null) return false;
            OnRequestMediaUploadSlot(
                ctx,
                args.ObjectKey,
                args.OriginalFilename,
                args.ContentType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestMediaUploadSlot : Reducer, IReducerArgs
        {
            [DataMember(Name = "object_key")]
            public string ObjectKey;
            [DataMember(Name = "original_filename")]
            public string OriginalFilename;
            [DataMember(Name = "content_type")]
            public string ContentType;

            public RequestMediaUploadSlot(
                string ObjectKey,
                string OriginalFilename,
                string ContentType
            )
            {
                this.ObjectKey = ObjectKey;
                this.OriginalFilename = OriginalFilename;
                this.ContentType = ContentType;
            }

            public RequestMediaUploadSlot()
            {
                this.ObjectKey = "";
                this.OriginalFilename = "";
                this.ContentType = "";
            }

            string IReducerArgs.ReducerName => "request_media_upload_slot";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RequestMediaUploadSlotFlags;
        public void RequestMediaUploadSlot(CallReducerFlags flags) => RequestMediaUploadSlotFlags = flags;
    }
}
