// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendDirectMessageHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Identity> recipients, string content);
        public event SendDirectMessageHandler? OnSendDirectMessage;

        public void SendDirectMessage(System.Collections.Generic.List<SpacetimeDB.Identity> recipients, string content)
        {
            conn.InternalCallReducer(new Reducer.SendDirectMessage(recipients, content), this.SetCallReducerFlags.SendDirectMessageFlags);
        }

        public bool InvokeSendDirectMessage(ReducerEventContext ctx, Reducer.SendDirectMessage args)
        {
            if (OnSendDirectMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendDirectMessage(
                ctx,
                args.Recipients,
                args.Content
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendDirectMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "recipients")]
            public System.Collections.Generic.List<SpacetimeDB.Identity> Recipients;
            [DataMember(Name = "content")]
            public string Content;

            public SendDirectMessage(
                System.Collections.Generic.List<SpacetimeDB.Identity> Recipients,
                string Content
            )
            {
                this.Recipients = Recipients;
                this.Content = Content;
            }

            public SendDirectMessage()
            {
                this.Recipients = new();
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "send_direct_message";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendDirectMessageFlags;
        public void SendDirectMessage(CallReducerFlags flags) => SendDirectMessageFlags = flags;
    }
}
