// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendConversationMessageHandler(ReducerEventContext ctx, ulong conversationId, string content);
        public event SendConversationMessageHandler? OnSendConversationMessage;

        public void SendConversationMessage(ulong conversationId, string content)
        {
            conn.InternalCallReducer(new Reducer.SendConversationMessage(conversationId, content), this.SetCallReducerFlags.SendConversationMessageFlags);
        }

        public bool InvokeSendConversationMessage(ReducerEventContext ctx, Reducer.SendConversationMessage args)
        {
            if (OnSendConversationMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendConversationMessage(
                ctx,
                args.ConversationId,
                args.Content
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendConversationMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "conversation_id")]
            public ulong ConversationId;
            [DataMember(Name = "content")]
            public string Content;

            public SendConversationMessage(
                ulong ConversationId,
                string Content
            )
            {
                this.ConversationId = ConversationId;
                this.Content = Content;
            }

            public SendConversationMessage()
            {
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "send_conversation_message";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendConversationMessageFlags;
        public void SendConversationMessage(CallReducerFlags flags) => SendConversationMessageFlags = flags;
    }
}
