// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryApproveOrganizationMemberRequestHandler(ReducerEventContext ctx, ulong requestId);
        public event TryApproveOrganizationMemberRequestHandler? OnTryApproveOrganizationMemberRequest;

        public void TryApproveOrganizationMemberRequest(ulong requestId)
        {
            conn.InternalCallReducer(new Reducer.TryApproveOrganizationMemberRequest(requestId), this.SetCallReducerFlags.TryApproveOrganizationMemberRequestFlags);
        }

        public bool InvokeTryApproveOrganizationMemberRequest(ReducerEventContext ctx, Reducer.TryApproveOrganizationMemberRequest args)
        {
            if (OnTryApproveOrganizationMemberRequest == null) return false;
            OnTryApproveOrganizationMemberRequest(
                ctx,
                args.RequestId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryApproveOrganizationMemberRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;

            public TryApproveOrganizationMemberRequest(ulong RequestId)
            {
                this.RequestId = RequestId;
            }

            public TryApproveOrganizationMemberRequest()
            {
            }

            string IReducerArgs.ReducerName => "try_approve_organization_member_request";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryApproveOrganizationMemberRequestFlags;
        public void TryApproveOrganizationMemberRequest(CallReducerFlags flags) => TryApproveOrganizationMemberRequestFlags = flags;
    }
}
