// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryCreateProtocolStateHandler(ReducerEventContext ctx, uint protocolId, uint organizationId, string state);
        public event TryCreateProtocolStateHandler? OnTryCreateProtocolState;

        public void TryCreateProtocolState(uint protocolId, uint organizationId, string state)
        {
            conn.InternalCallReducer(new Reducer.TryCreateProtocolState(protocolId, organizationId, state), this.SetCallReducerFlags.TryCreateProtocolStateFlags);
        }

        public bool InvokeTryCreateProtocolState(ReducerEventContext ctx, Reducer.TryCreateProtocolState args)
        {
            if (OnTryCreateProtocolState == null) return false;
            OnTryCreateProtocolState(
                ctx,
                args.ProtocolId,
                args.OrganizationId,
                args.State
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryCreateProtocolState : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_id")]
            public uint ProtocolId;
            [DataMember(Name = "organization_id")]
            public uint OrganizationId;
            [DataMember(Name = "state")]
            public string State;

            public TryCreateProtocolState(
                uint ProtocolId,
                uint OrganizationId,
                string State
            )
            {
                this.ProtocolId = ProtocolId;
                this.OrganizationId = OrganizationId;
                this.State = State;
            }

            public TryCreateProtocolState()
            {
                this.State = "";
            }

            string IReducerArgs.ReducerName => "try_create_protocol_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryCreateProtocolStateFlags;
        public void TryCreateProtocolState(CallReducerFlags flags) => TryCreateProtocolStateFlags = flags;
    }
}
