// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryCreateProtocolHandler(ReducerEventContext ctx, string name, string content, bool isPublic, uint organizationId);
        public event TryCreateProtocolHandler? OnTryCreateProtocol;

        public void TryCreateProtocol(string name, string content, bool isPublic, uint organizationId)
        {
            conn.InternalCallReducer(new Reducer.TryCreateProtocol(name, content, isPublic, organizationId), this.SetCallReducerFlags.TryCreateProtocolFlags);
        }

        public bool InvokeTryCreateProtocol(ReducerEventContext ctx, Reducer.TryCreateProtocol args)
        {
            if (OnTryCreateProtocol == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryCreateProtocol(
                ctx,
                args.Name,
                args.Content,
                args.IsPublic,
                args.OrganizationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryCreateProtocol : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "content")]
            public string Content;
            [DataMember(Name = "is_public")]
            public bool IsPublic;
            [DataMember(Name = "organization_id")]
            public uint OrganizationId;

            public TryCreateProtocol(
                string Name,
                string Content,
                bool IsPublic,
                uint OrganizationId
            )
            {
                this.Name = Name;
                this.Content = Content;
                this.IsPublic = IsPublic;
                this.OrganizationId = OrganizationId;
            }

            public TryCreateProtocol()
            {
                this.Name = "";
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "try_create_protocol";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryCreateProtocolFlags;
        public void TryCreateProtocol(CallReducerFlags flags) => TryCreateProtocolFlags = flags;
    }
}
