// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryCancelScheduledTaskHandler(ReducerEventContext ctx, ulong taskId);
        public event TryCancelScheduledTaskHandler? OnTryCancelScheduledTask;

        public void TryCancelScheduledTask(ulong taskId)
        {
            conn.InternalCallReducer(new Reducer.TryCancelScheduledTask(taskId), this.SetCallReducerFlags.TryCancelScheduledTaskFlags);
        }

        public bool InvokeTryCancelScheduledTask(ReducerEventContext ctx, Reducer.TryCancelScheduledTask args)
        {
            if (OnTryCancelScheduledTask == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryCancelScheduledTask(
                ctx,
                args.TaskId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryCancelScheduledTask : Reducer, IReducerArgs
        {
            [DataMember(Name = "task_id")]
            public ulong TaskId;

            public TryCancelScheduledTask(ulong TaskId)
            {
                this.TaskId = TaskId;
            }

            public TryCancelScheduledTask()
            {
            }

            string IReducerArgs.ReducerName => "try_cancel_scheduled_task";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryCancelScheduledTaskFlags;
        public void TryCancelScheduledTask(CallReducerFlags flags) => TryCancelScheduledTaskFlags = flags;
    }
}
