// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryCompleteScheduledTaskHandler(ReducerEventContext ctx, ulong taskId);
        public event TryCompleteScheduledTaskHandler? OnTryCompleteScheduledTask;

        public void TryCompleteScheduledTask(ulong taskId)
        {
            conn.InternalCallReducer(new Reducer.TryCompleteScheduledTask(taskId), this.SetCallReducerFlags.TryCompleteScheduledTaskFlags);
        }

        public bool InvokeTryCompleteScheduledTask(ReducerEventContext ctx, Reducer.TryCompleteScheduledTask args)
        {
            if (OnTryCompleteScheduledTask == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryCompleteScheduledTask(
                ctx,
                args.TaskId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryCompleteScheduledTask : Reducer, IReducerArgs
        {
            [DataMember(Name = "task_id")]
            public ulong TaskId;

            public TryCompleteScheduledTask(ulong TaskId)
            {
                this.TaskId = TaskId;
            }

            public TryCompleteScheduledTask()
            {
            }

            string IReducerArgs.ReducerName => "try_complete_scheduled_task";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryCompleteScheduledTaskFlags;
        public void TryCompleteScheduledTask(CallReducerFlags flags) => TryCompleteScheduledTaskFlags = flags;
    }
}
