// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryCreateOrganizationHandler(ReducerEventContext ctx, string name);
        public event TryCreateOrganizationHandler? OnTryCreateOrganization;

        public void TryCreateOrganization(string name)
        {
            conn.InternalCallReducer(new Reducer.TryCreateOrganization(name), this.SetCallReducerFlags.TryCreateOrganizationFlags);
        }

        public bool InvokeTryCreateOrganization(ReducerEventContext ctx, Reducer.TryCreateOrganization args)
        {
            if (OnTryCreateOrganization == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryCreateOrganization(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryCreateOrganization : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public TryCreateOrganization(string Name)
            {
                this.Name = Name;
            }

            public TryCreateOrganization()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "try_create_organization";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryCreateOrganizationFlags;
        public void TryCreateOrganization(CallReducerFlags flags) => TryCreateOrganizationFlags = flags;
    }
}
