// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryDenyOrganizationMemberRequestHandler(ReducerEventContext ctx, ulong requestId);
        public event TryDenyOrganizationMemberRequestHandler? OnTryDenyOrganizationMemberRequest;

        public void TryDenyOrganizationMemberRequest(ulong requestId)
        {
            conn.InternalCallReducer(new Reducer.TryDenyOrganizationMemberRequest(requestId), this.SetCallReducerFlags.TryDenyOrganizationMemberRequestFlags);
        }

        public bool InvokeTryDenyOrganizationMemberRequest(ReducerEventContext ctx, Reducer.TryDenyOrganizationMemberRequest args)
        {
            if (OnTryDenyOrganizationMemberRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryDenyOrganizationMemberRequest(
                ctx,
                args.RequestId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryDenyOrganizationMemberRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;

            public TryDenyOrganizationMemberRequest(ulong RequestId)
            {
                this.RequestId = RequestId;
            }

            public TryDenyOrganizationMemberRequest()
            {
            }

            string IReducerArgs.ReducerName => "try_deny_organization_member_request";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryDenyOrganizationMemberRequestFlags;
        public void TryDenyOrganizationMemberRequest(CallReducerFlags flags) => TryDenyOrganizationMemberRequestFlags = flags;
    }
}
