// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryDeleteProtocolHandler(ReducerEventContext ctx, uint protocolId);
        public event TryDeleteProtocolHandler? OnTryDeleteProtocol;

        public void TryDeleteProtocol(uint protocolId)
        {
            conn.InternalCallReducer(new Reducer.TryDeleteProtocol(protocolId), this.SetCallReducerFlags.TryDeleteProtocolFlags);
        }

        public bool InvokeTryDeleteProtocol(ReducerEventContext ctx, Reducer.TryDeleteProtocol args)
        {
            if (OnTryDeleteProtocol == null) return false;
            OnTryDeleteProtocol(
                ctx,
                args.ProtocolId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryDeleteProtocol : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_id")]
            public uint ProtocolId;

            public TryDeleteProtocol(uint ProtocolId)
            {
                this.ProtocolId = ProtocolId;
            }

            public TryDeleteProtocol()
            {
            }

            string IReducerArgs.ReducerName => "try_delete_protocol";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryDeleteProtocolFlags;
        public void TryDeleteProtocol(CallReducerFlags flags) => TryDeleteProtocolFlags = flags;
    }
}
