// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryDeleteProtocolStateHandler(ReducerEventContext ctx, uint protocolStateId);
        public event TryDeleteProtocolStateHandler? OnTryDeleteProtocolState;

        public void TryDeleteProtocolState(uint protocolStateId)
        {
            conn.InternalCallReducer(new Reducer.TryDeleteProtocolState(protocolStateId), this.SetCallReducerFlags.TryDeleteProtocolStateFlags);
        }

        public bool InvokeTryDeleteProtocolState(ReducerEventContext ctx, Reducer.TryDeleteProtocolState args)
        {
            if (OnTryDeleteProtocolState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryDeleteProtocolState(
                ctx,
                args.ProtocolStateId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryDeleteProtocolState : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_state_id")]
            public uint ProtocolStateId;

            public TryDeleteProtocolState(uint ProtocolStateId)
            {
                this.ProtocolStateId = ProtocolStateId;
            }

            public TryDeleteProtocolState()
            {
            }

            string IReducerArgs.ReducerName => "try_delete_protocol_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryDeleteProtocolStateFlags;
        public void TryDeleteProtocolState(CallReducerFlags flags) => TryDeleteProtocolStateFlags = flags;
    }
}
