// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryDeleteOrganizationNoticeHandler(ReducerEventContext ctx, ulong noticeId);
        public event TryDeleteOrganizationNoticeHandler? OnTryDeleteOrganizationNotice;

        public void TryDeleteOrganizationNotice(ulong noticeId)
        {
            conn.InternalCallReducer(new Reducer.TryDeleteOrganizationNotice(noticeId), this.SetCallReducerFlags.TryDeleteOrganizationNoticeFlags);
        }

        public bool InvokeTryDeleteOrganizationNotice(ReducerEventContext ctx, Reducer.TryDeleteOrganizationNotice args)
        {
            if (OnTryDeleteOrganizationNotice == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryDeleteOrganizationNotice(
                ctx,
                args.NoticeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryDeleteOrganizationNotice : Reducer, IReducerArgs
        {
            [DataMember(Name = "notice_id")]
            public ulong NoticeId;

            public TryDeleteOrganizationNotice(ulong NoticeId)
            {
                this.NoticeId = NoticeId;
            }

            public TryDeleteOrganizationNotice()
            {
            }

            string IReducerArgs.ReducerName => "try_delete_organization_notice";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryDeleteOrganizationNoticeFlags;
        public void TryDeleteOrganizationNotice(CallReducerFlags flags) => TryDeleteOrganizationNoticeFlags = flags;
    }
}
