// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryEditProtocolHandler(ReducerEventContext ctx, uint protocolId, string newName, string content, bool isPublic, uint? newOwnerOrganizationId);
        public event TryEditProtocolHandler? OnTryEditProtocol;

        public void TryEditProtocol(uint protocolId, string newName, string content, bool isPublic, uint? newOwnerOrganizationId)
        {
            conn.InternalCallReducer(new Reducer.TryEditProtocol(protocolId, newName, content, isPublic, newOwnerOrganizationId), this.SetCallReducerFlags.TryEditProtocolFlags);
        }

        public bool InvokeTryEditProtocol(ReducerEventContext ctx, Reducer.TryEditProtocol args)
        {
            if (OnTryEditProtocol == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryEditProtocol(
                ctx,
                args.ProtocolId,
                args.NewName,
                args.Content,
                args.IsPublic,
                args.NewOwnerOrganizationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryEditProtocol : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_id")]
            public uint ProtocolId;
            [DataMember(Name = "new_name")]
            public string NewName;
            [DataMember(Name = "content")]
            public string Content;
            [DataMember(Name = "is_public")]
            public bool IsPublic;
            [DataMember(Name = "new_owner_organization_id")]
            public uint? NewOwnerOrganizationId;

            public TryEditProtocol(
                uint ProtocolId,
                string NewName,
                string Content,
                bool IsPublic,
                uint? NewOwnerOrganizationId
            )
            {
                this.ProtocolId = ProtocolId;
                this.NewName = NewName;
                this.Content = Content;
                this.IsPublic = IsPublic;
                this.NewOwnerOrganizationId = NewOwnerOrganizationId;
            }

            public TryEditProtocol()
            {
                this.NewName = "";
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "try_edit_protocol";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryEditProtocolFlags;
        public void TryEditProtocol(CallReducerFlags flags) => TryEditProtocolFlags = flags;
    }
}
