// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryEditProtocolStateHandler(ReducerEventContext ctx, uint protocolStateId, string newState);
        public event TryEditProtocolStateHandler? OnTryEditProtocolState;

        public void TryEditProtocolState(uint protocolStateId, string newState)
        {
            conn.InternalCallReducer(new Reducer.TryEditProtocolState(protocolStateId, newState), this.SetCallReducerFlags.TryEditProtocolStateFlags);
        }

        public bool InvokeTryEditProtocolState(ReducerEventContext ctx, Reducer.TryEditProtocolState args)
        {
            if (OnTryEditProtocolState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryEditProtocolState(
                ctx,
                args.ProtocolStateId,
                args.NewState
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryEditProtocolState : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_state_id")]
            public uint ProtocolStateId;
            [DataMember(Name = "new_state")]
            public string NewState;

            public TryEditProtocolState(
                uint ProtocolStateId,
                string NewState
            )
            {
                this.ProtocolStateId = ProtocolStateId;
                this.NewState = NewState;
            }

            public TryEditProtocolState()
            {
                this.NewState = "";
            }

            string IReducerArgs.ReducerName => "try_edit_protocol_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryEditProtocolStateFlags;
        public void TryEditProtocolState(CallReducerFlags flags) => TryEditProtocolStateFlags = flags;
    }
}
