// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryForkProtocolHandler(ReducerEventContext ctx, uint originalProtocolId, string newName, bool newIsPublic);
        public event TryForkProtocolHandler? OnTryForkProtocol;

        public void TryForkProtocol(uint originalProtocolId, string newName, bool newIsPublic)
        {
            conn.InternalCallReducer(new Reducer.TryForkProtocol(originalProtocolId, newName, newIsPublic), this.SetCallReducerFlags.TryForkProtocolFlags);
        }

        public bool InvokeTryForkProtocol(ReducerEventContext ctx, Reducer.TryForkProtocol args)
        {
            if (OnTryForkProtocol == null) return false;
            OnTryForkProtocol(
                ctx,
                args.OriginalProtocolId,
                args.NewName,
                args.NewIsPublic
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryForkProtocol : Reducer, IReducerArgs
        {
            [DataMember(Name = "original_protocol_id")]
            public uint OriginalProtocolId;
            [DataMember(Name = "new_name")]
            public string NewName;
            [DataMember(Name = "new_is_public")]
            public bool NewIsPublic;

            public TryForkProtocol(
                uint OriginalProtocolId,
                string NewName,
                bool NewIsPublic
            )
            {
                this.OriginalProtocolId = OriginalProtocolId;
                this.NewName = NewName;
                this.NewIsPublic = NewIsPublic;
            }

            public TryForkProtocol()
            {
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "try_fork_protocol";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryForkProtocolFlags;
        public void TryForkProtocol(CallReducerFlags flags) => TryForkProtocolFlags = flags;
    }
}
