// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryLeaveOrganizationHandler(ReducerEventContext ctx, uint organizationId);
        public event TryLeaveOrganizationHandler? OnTryLeaveOrganization;

        public void TryLeaveOrganization(uint organizationId)
        {
            conn.InternalCallReducer(new Reducer.TryLeaveOrganization(organizationId), this.SetCallReducerFlags.TryLeaveOrganizationFlags);
        }

        public bool InvokeTryLeaveOrganization(ReducerEventContext ctx, Reducer.TryLeaveOrganization args)
        {
            if (OnTryLeaveOrganization == null) return false;
            OnTryLeaveOrganization(
                ctx,
                args.OrganizationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryLeaveOrganization : Reducer, IReducerArgs
        {
            [DataMember(Name = "organization_id")]
            public uint OrganizationId;

            public TryLeaveOrganization(uint OrganizationId)
            {
                this.OrganizationId = OrganizationId;
            }

            public TryLeaveOrganization()
            {
            }

            string IReducerArgs.ReducerName => "try_leave_organization";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryLeaveOrganizationFlags;
        public void TryLeaveOrganization(CallReducerFlags flags) => TryLeaveOrganizationFlags = flags;
    }
}
