// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryPostOrganizationNoticeHandler(ReducerEventContext ctx, uint organizationId, string content, ulong durationSeconds);
        public event TryPostOrganizationNoticeHandler? OnTryPostOrganizationNotice;

        public void TryPostOrganizationNotice(uint organizationId, string content, ulong durationSeconds)
        {
            conn.InternalCallReducer(new Reducer.TryPostOrganizationNotice(organizationId, content, durationSeconds), this.SetCallReducerFlags.TryPostOrganizationNoticeFlags);
        }

        public bool InvokeTryPostOrganizationNotice(ReducerEventContext ctx, Reducer.TryPostOrganizationNotice args)
        {
            if (OnTryPostOrganizationNotice == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryPostOrganizationNotice(
                ctx,
                args.OrganizationId,
                args.Content,
                args.DurationSeconds
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryPostOrganizationNotice : Reducer, IReducerArgs
        {
            [DataMember(Name = "organization_id")]
            public uint OrganizationId;
            [DataMember(Name = "content")]
            public string Content;
            [DataMember(Name = "duration_seconds")]
            public ulong DurationSeconds;

            public TryPostOrganizationNotice(
                uint OrganizationId,
                string Content,
                ulong DurationSeconds
            )
            {
                this.OrganizationId = OrganizationId;
                this.Content = Content;
                this.DurationSeconds = DurationSeconds;
            }

            public TryPostOrganizationNotice()
            {
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "try_post_organization_notice";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryPostOrganizationNoticeFlags;
        public void TryPostOrganizationNotice(CallReducerFlags flags) => TryPostOrganizationNoticeFlags = flags;
    }
}
