// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryRollbackProtocolHandler(ReducerEventContext ctx, uint protocolId);
        public event TryRollbackProtocolHandler? OnTryRollbackProtocol;

        public void TryRollbackProtocol(uint protocolId)
        {
            conn.InternalCallReducer(new Reducer.TryRollbackProtocol(protocolId), this.SetCallReducerFlags.TryRollbackProtocolFlags);
        }

        public bool InvokeTryRollbackProtocol(ReducerEventContext ctx, Reducer.TryRollbackProtocol args)
        {
            if (OnTryRollbackProtocol == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryRollbackProtocol(
                ctx,
                args.ProtocolId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryRollbackProtocol : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_id")]
            public uint ProtocolId;

            public TryRollbackProtocol(uint ProtocolId)
            {
                this.ProtocolId = ProtocolId;
            }

            public TryRollbackProtocol()
            {
            }

            string IReducerArgs.ReducerName => "try_rollback_protocol";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryRollbackProtocolFlags;
        public void TryRollbackProtocol(CallReducerFlags flags) => TryRollbackProtocolFlags = flags;
    }
}
