// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryStartScheduledTaskHandler(ReducerEventContext ctx, ulong taskId);
        public event TryStartScheduledTaskHandler? OnTryStartScheduledTask;

        public void TryStartScheduledTask(ulong taskId)
        {
            conn.InternalCallReducer(new Reducer.TryStartScheduledTask(taskId), this.SetCallReducerFlags.TryStartScheduledTaskFlags);
        }

        public bool InvokeTryStartScheduledTask(ReducerEventContext ctx, Reducer.TryStartScheduledTask args)
        {
            if (OnTryStartScheduledTask == null) return false;
            OnTryStartScheduledTask(
                ctx,
                args.TaskId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryStartScheduledTask : Reducer, IReducerArgs
        {
            [DataMember(Name = "task_id")]
            public ulong TaskId;

            public TryStartScheduledTask(ulong TaskId)
            {
                this.TaskId = TaskId;
            }

            public TryStartScheduledTask()
            {
            }

            string IReducerArgs.ReducerName => "try_start_scheduled_task";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryStartScheduledTaskFlags;
        public void TryStartScheduledTask(CallReducerFlags flags) => TryStartScheduledTaskFlags = flags;
    }
}
