// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryUnsaveProtocolHandler(ReducerEventContext ctx, uint protocolId);
        public event TryUnsaveProtocolHandler? OnTryUnsaveProtocol;

        public void TryUnsaveProtocol(uint protocolId)
        {
            conn.InternalCallReducer(new Reducer.TryUnsaveProtocol(protocolId), this.SetCallReducerFlags.TryUnsaveProtocolFlags);
        }

        public bool InvokeTryUnsaveProtocol(ReducerEventContext ctx, Reducer.TryUnsaveProtocol args)
        {
            if (OnTryUnsaveProtocol == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryUnsaveProtocol(
                ctx,
                args.ProtocolId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryUnsaveProtocol : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_id")]
            public uint ProtocolId;

            public TryUnsaveProtocol(uint ProtocolId)
            {
                this.ProtocolId = ProtocolId;
            }

            public TryUnsaveProtocol()
            {
            }

            string IReducerArgs.ReducerName => "try_unsave_protocol";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryUnsaveProtocolFlags;
        public void TryUnsaveProtocol(CallReducerFlags flags) => TryUnsaveProtocolFlags = flags;
    }
}
