// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateOrganizationNameHandler(ReducerEventContext ctx, uint organizationId, string newName);
        public event UpdateOrganizationNameHandler? OnUpdateOrganizationName;

        public void UpdateOrganizationName(uint organizationId, string newName)
        {
            conn.InternalCallReducer(new Reducer.UpdateOrganizationName(organizationId, newName), this.SetCallReducerFlags.UpdateOrganizationNameFlags);
        }

        public bool InvokeUpdateOrganizationName(ReducerEventContext ctx, Reducer.UpdateOrganizationName args)
        {
            if (OnUpdateOrganizationName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateOrganizationName(
                ctx,
                args.OrganizationId,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateOrganizationName : Reducer, IReducerArgs
        {
            [DataMember(Name = "organization_id")]
            public uint OrganizationId;
            [DataMember(Name = "new_name")]
            public string NewName;

            public UpdateOrganizationName(
                uint OrganizationId,
                string NewName
            )
            {
                this.OrganizationId = OrganizationId;
                this.NewName = NewName;
            }

            public UpdateOrganizationName()
            {
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "update_organization_name";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateOrganizationNameFlags;
        public void UpdateOrganizationName(CallReducerFlags flags) => UpdateOrganizationNameFlags = flags;
    }
}
