// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateUserProfileBioHandler(ReducerEventContext ctx, string newBio);
        public event UpdateUserProfileBioHandler? OnUpdateUserProfileBio;

        public void UpdateUserProfileBio(string newBio)
        {
            conn.InternalCallReducer(new Reducer.UpdateUserProfileBio(newBio), this.SetCallReducerFlags.UpdateUserProfileBioFlags);
        }

        public bool InvokeUpdateUserProfileBio(ReducerEventContext ctx, Reducer.UpdateUserProfileBio args)
        {
            if (OnUpdateUserProfileBio == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateUserProfileBio(
                ctx,
                args.NewBio
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateUserProfileBio : Reducer, IReducerArgs
        {
            [DataMember(Name = "new_bio")]
            public string NewBio;

            public UpdateUserProfileBio(string NewBio)
            {
                this.NewBio = NewBio;
            }

            public UpdateUserProfileBio()
            {
                this.NewBio = "";
            }

            string IReducerArgs.ReducerName => "update_user_profile_bio";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateUserProfileBioFlags;
        public void UpdateUserProfileBio(CallReducerFlags flags) => UpdateUserProfileBioFlags = flags;
    }
}
