// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateOrganizationDescriptionHandler(ReducerEventContext ctx, uint organizationId, string newDescription);
        public event UpdateOrganizationDescriptionHandler? OnUpdateOrganizationDescription;

        public void UpdateOrganizationDescription(uint organizationId, string newDescription)
        {
            conn.InternalCallReducer(new Reducer.UpdateOrganizationDescription(organizationId, newDescription), this.SetCallReducerFlags.UpdateOrganizationDescriptionFlags);
        }

        public bool InvokeUpdateOrganizationDescription(ReducerEventContext ctx, Reducer.UpdateOrganizationDescription args)
        {
            if (OnUpdateOrganizationDescription == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateOrganizationDescription(
                ctx,
                args.OrganizationId,
                args.NewDescription
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateOrganizationDescription : Reducer, IReducerArgs
        {
            [DataMember(Name = "organization_id")]
            public uint OrganizationId;
            [DataMember(Name = "new_description")]
            public string NewDescription;

            public UpdateOrganizationDescription(
                uint OrganizationId,
                string NewDescription
            )
            {
                this.OrganizationId = OrganizationId;
                this.NewDescription = NewDescription;
            }

            public UpdateOrganizationDescription()
            {
                this.NewDescription = "";
            }

            string IReducerArgs.ReducerName => "update_organization_description";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateOrganizationDescriptionFlags;
        public void UpdateOrganizationDescription(CallReducerFlags flags) => UpdateOrganizationDescriptionFlags = flags;
    }
}
