// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateProtocolDescriptionHandler(ReducerEventContext ctx, uint protocolId, string newDescription);
        public event UpdateProtocolDescriptionHandler? OnUpdateProtocolDescription;

        public void UpdateProtocolDescription(uint protocolId, string newDescription)
        {
            conn.InternalCallReducer(new Reducer.UpdateProtocolDescription(protocolId, newDescription), this.SetCallReducerFlags.UpdateProtocolDescriptionFlags);
        }

        public bool InvokeUpdateProtocolDescription(ReducerEventContext ctx, Reducer.UpdateProtocolDescription args)
        {
            if (OnUpdateProtocolDescription == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateProtocolDescription(
                ctx,
                args.ProtocolId,
                args.NewDescription
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateProtocolDescription : Reducer, IReducerArgs
        {
            [DataMember(Name = "protocol_id")]
            public uint ProtocolId;
            [DataMember(Name = "new_description")]
            public string NewDescription;

            public UpdateProtocolDescription(
                uint ProtocolId,
                string NewDescription
            )
            {
                this.ProtocolId = ProtocolId;
                this.NewDescription = NewDescription;
            }

            public UpdateProtocolDescription()
            {
                this.NewDescription = "";
            }

            string IReducerArgs.ReducerName => "update_protocol_description";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateProtocolDescriptionFlags;
        public void UpdateProtocolDescription(CallReducerFlags flags) => UpdateProtocolDescriptionFlags = flags;
    }
}
