// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateUserProfileNameHandler(ReducerEventContext ctx, string newName);
        public event UpdateUserProfileNameHandler? OnUpdateUserProfileName;

        public void UpdateUserProfileName(string newName)
        {
            conn.InternalCallReducer(new Reducer.UpdateUserProfileName(newName), this.SetCallReducerFlags.UpdateUserProfileNameFlags);
        }

        public bool InvokeUpdateUserProfileName(ReducerEventContext ctx, Reducer.UpdateUserProfileName args)
        {
            if (OnUpdateUserProfileName == null) return false;
            OnUpdateUserProfileName(
                ctx,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateUserProfileName : Reducer, IReducerArgs
        {
            [DataMember(Name = "new_name")]
            public string NewName;

            public UpdateUserProfileName(string NewName)
            {
                this.NewName = NewName;
            }

            public UpdateUserProfileName()
            {
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "update_user_profile_name";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateUserProfileNameFlags;
        public void UpdateUserProfileName(CallReducerFlags flags) => UpdateUserProfileNameFlags = flags;
    }
}
